### ISSUE TITLE
API call defaults to outputsize=compact

### ISSUE THREAD

**Issue by ryandjones** [PatrickAlphaVantage/tableau_wdc#5]
According to the documentation on [Alpha Vantage](https://www.alphavantage.co/documentation/), there is an optional API parameter called "outputsize" which, when not explicitly defined, defaults to a value of "compact" which returns only the most recent 100 rows.

As an Alpha Vantage WDC user, I would like to see an option within the Stock Time Series area and "Daily" Data Type to select either "compact" to return just 100 rows or "full" to return the fully-available data set so that I can retrieve a full history when required for my analysis.

**Comment by PatrickAlphaC** [comment]
Great suggestion! I'll look to add that now

**Comment by PatrickAlphaC** [comment]
I've defaulted it now so that it always pulls the full dataset, and you can cut it down in tableau as needed. Thanks for the suggestion!

**Comment by ryandjones** [comment]
Incredible.  Just tested, works like a charm.
